name: XM to OpenIPC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setenv
        run: |
          TAG_NAME="latest"
          RELEASE_NAME="OpenIPC Firmware"
          PRERELEASE=true
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
          echo "PRERELEASE=$PRERELEASE" >> $GITHUB_ENV
      - name: Install dependencies
        run: sudo apt-get update; sudo apt-get install u-boot-tools zip
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Fetch OpenIPC release
        run: |
          wget -q https://github.com/OpenIPC/firmware/releases/download/latest/openipc.hi3516cv100-br.tgz
          wget -q https://github.com/OpenIPC/firmware/releases/download/latest/openipc.hi3518cv100-br.tgz
          wget -q https://github.com/OpenIPC/firmware/releases/download/latest/openipc.hi3518ev100-br.tgz
          wget -q https://github.com/OpenIPC/firmware/releases/download/latest/openipc.hi3516cv200-br.tgz
          wget -q https://github.com/OpenIPC/firmware/releases/download/latest/openipc.hi3516dv100-br.tgz
          wget -q https://github.com/OpenIPC/firmware/releases/download/latest/openipc.hi3518ev200-br.tgz
          wget -q https://github.com/OpenIPC/firmware/releases/download/latest/openipc.hi3516cv300-br.tgz
          wget -q https://github.com/OpenIPC/firmware/releases/download/latest/openipc.hi3516ev100-br.tgz
          wget -q https://github.com/OpenIPC/firmware/releases/download/latest/openipc.hi3516ev300-br.tgz
          wget -q https://github.com/OpenIPC/firmware/releases/download/latest/openipc.hi3516ev200-br.tgz
          wget -q https://github.com/OpenIPC/firmware/releases/download/latest/openipc.hi3536cv100-br.tgz
          wget -q https://github.com/OpenIPC/firmware/releases/download/latest/openipc.hi3536dv100-br.tgz
          wget -q https://github.com/OpenIPC/firmware/releases/download/latest/openipc.gk7205v200-br.tgz
          wget -q https://github.com/OpenIPC/firmware/releases/download/latest/openipc.gk7205v300-br.tgz
          wget -q https://github.com/OpenIPC/firmware/releases/download/latest/openipc.gk7605v100-br.tgz
          wget -q https://github.com/OpenIPC/firmware/releases/download/latest/openipc.xm530-br.tgz
          wget -q https://github.com/OpenIPC/firmware/releases/download/latest/openipc.xm510-br.tgz
          wget -q https://github.com/OpenIPC/firmware/releases/download/latest/openipc.nt98562-br.tgz
          wget -q https://github.com/OpenIPC/firmware/releases/download/latest/openipc.nt98566-br.tgz
      - name: Create firmwares
        run: |
            export RUN="$GITHUB_WORKSPACE/.github/workflows/_xm2oipc.sh"
            export OUTPUTDIR="$GITHUB_WORKSPACE/out"
            chmod +x $RUN
            SOC="hi3518cv100" TOTALMEM="64M" HARDWARE="50H10L" DEVID="00001510" FLASH_SIZE="0x1000000" $RUN
            SOC="hi3516cv100" TOTALMEM="128M" HARDWARE="50H20L" DEVID="00001520" FLASH_SIZE="0x1000000" $RUN
            SOC="hi3518cv100" TOTALMEM="64M" HARDWARE="53H13" DEVID="00001531" FLASH_SIZE="0x1000000" $RUN
            SOC="hi3516cv100" TOTALMEM="128M" HARDWARE="53H20L" DEVID="00001532" FLASH_SIZE="0x1000000" $RUN
            
            SOC="hi3518cv100" TOTALMEM="64M" HARDWARE="50H10L_S39" DEVID="00002510" FLASH_SIZE="0x800000" $RUN
            SOC="hi3516cv100" TOTALMEM="128M" HARDWARE="50H20L_S39" DEVID="00002520" FLASH_SIZE="0x800000" $RUN
            SOC="hi3518cv100" TOTALMEM="64M" HARDWARE="53H13_S39" DEVID="00002531" FLASH_SIZE="0x800000" $RUN
            SOC="hi3516cv100" TOTALMEM="128M" HARDWARE="53H20L_S39" DEVID="00002532" FLASH_SIZE="0x800000" $RUN

            SOC="hi3518ev100" TOTALMEM="64M" HARDWARE="HI3518E_50H10L_S39" DEVID="00006510" FLASH_SIZE="0x800000" $RUN
            SOC="hi3518ev100" TOTALMEM="64M" HARDWARE="HI3518E_53H13_S39" DEVID="00006531" FLASH_SIZE="0x800000" $RUN

            SOC="hi3518ev200" TOTALMEM="64M" HARDWARE="50H10L_S38" DEVID="00018510" FLASH_SIZE="0x800000" $RUN
            SOC="hi3518ev200" TOTALMEM="64M" HARDWARE="50H20L_18EV200_S38" DEVID="00018520" FLASH_SIZE="0x800000" $RUN
            SOC="hi3516cv200" TOTALMEM="64M" HARDWARE="53H20L_16CV200_S38" DEVID="00018532" FLASH_SIZE="0x800000" $RUN

            SOC="hi3516dv100" TOTALMEM="256M" HARDWARE="83H50" DEVID="00010850" FLASH_SIZE="0x1000000" $RUN
            SOC="hi3516dv100" TOTALMEM="128M" HARDWARE="HI3516D_83H30" DEVID="00014830" FLASH_SIZE="0x1000000" $RUN
            SOC="hi3516dv100" TOTALMEM="128M" HARDWARE="HI3516D_83H40" DEVID="00014840" FLASH_SIZE="0x1000000" $RUN
            SOC="hi3516dv100" TOTALMEM="128M" HARDWARE="HI3516D_83H40AF" DEVID="00014843" FLASH_SIZE="0x1000000" $RUN
            SOC="hi3516dv100" TOTALMEM="128M" HARDWARE="HI3516D_83H20" DEVID="00014911" FLASH_SIZE="0x1000000" $RUN
            SOC="hi3516dv100" TOTALMEM="128M" HARDWARE="HI3516D_N81820" DEVID="00014914" FLASH_SIZE="0x1000000" $RUN
            SOC="hi3516dv100" TOTALMEM="128M" HARDWARE="HI3516D_83H50N" DEVID="00014927" FLASH_SIZE="0x1000000" $RUN

            SOC="hi3516ev100" TOTALMEM="64M" HARDWARE="HI3516EV100_50H20L_S38" DEVID="00035520" FLASH_SIZE="0x800000" $RUN
            SOC="hi3516cv300" TOTALMEM="128M" HARDWARE="50H20L" DEVID="00022520" FLASH_SIZE="0x800000" $RUN
            SOC="hi3516cv300" TOTALMEM="128M" HARDWARE="50H20L" DEVID="00031520" FLASH_SIZE="0x1000000" $RUN
            SOC="hi3516cv300" TOTALMEM="128M" HARDWARE="50H20L_SG" DEVID="000319AB" FLASH_SIZE="0x1000000" $RUN

            SOC="hi3516ev200" TOTALMEM="64M" HARDWARE="HI3516EV200_50H20AI_S38" DEVID="000559A7" FLASH_SIZE="0x800000" $RUN
            SOC="hi3516ev200" TOTALMEM="64M" HARDWARE="HI3516EV200_85H30AI_S38" DEVID="000559B0" FLASH_SIZE="0x800000" $RUN
            SOC="hi3516ev200" TOTALMEM="64M" HARDWARE="HI3516EV200_85HF30T_S38" DEVID="000559CD" FLASH_SIZE="0x800000" $RUN

            SOC="hi3516ev300" TOTALMEM="128M" HARDWARE="HI3516EV300_85H50AI" DEVID="000529B2" FLASH_SIZE="0x1000000" $RUN
            SOC="hi3516ev300" TOTALMEM="128M" HARDWARE="HI3516EV300_N80050YA" DEVID="000529D9" FLASH_SIZE="0x1000000" $RUN
            SOC="hi3516ev300" TOTALMEM="128M" HARDWARE="HI3516EV300_85HF50T" DEVID="000529E9" FLASH_SIZE="0x1000000" $RUN
            SOC="hi3516ev300" TOTALMEM="128M" HARDWARE="HI3516EV300_83H50AI_S38" DEVID="000589C9" FLASH_SIZE="0x800000" $RUN

            SOC="hi3536cv100" TOTALMEM="512M" HARDWARE="NBD8008R-U" DEVID="00000197" FLASH_SIZE="0x1000000" COMPAT="1" $RUN
            SOC="hi3536dv100" TOTALMEM="256M" HARDWARE="NBD8008R-PL" DEVID="00000202" FLASH_SIZE="0x1000000" COMPAT="1" $RUN

            SOC="gk7205v200" TOTALMEM="64M" HARDWARE="IPC_GK7205V200_50H20AI_S38" DEVID="000659A7" FLASH_SIZE="0x800000" $RUN
            SOC="gk7205v200" TOTALMEM="64M" HARDWARE="IPC_GK7205V200_85HF30T_S38" DEVID="000659CD" FLASH_SIZE="0x800000" $RUN

            SOC="gk7205v300" TOTALMEM="128M" HARDWARE="IPC_GK7205V300_85K50T" DEVID="000669H7" FLASH_SIZE="0x800000" $RUN

            SOC="gk7605v100" TOTALMEM="256M" HARDWARE="IPC_GK7605V100_83K50W_S38" DEVID="000669HC" FLASH_SIZE="0x800000" $RUN

            SOC="xm530" OSMEM="35M" TOTALMEM="64M" HARDWARE="XM530_80X20_8M" DEVID="00030678" FLASH_SIZE="0x800000" COMPAT="3" $RUN
            SOC="xm530" OSMEM="35M" TOTALMEM="64M" HARDWARE="XM530_85X20_8M" DEVID="0003068b" FLASH_SIZE="0x800000" COMPAT="3" $RUN
            SOC="xm530" OSMEM="35M" TOTALMEM="64M" HARDWARE="XM530_50X20-WG_8M" DEVID="000309C1" FLASH_SIZE="0x800000" COMPAT="3" $RUN
            SOC="xm530" OSMEM="35M" TOTALMEM="64M" HARDWARE="XM530_85X20T_8M" DEVID="000309E5" FLASH_SIZE="0x800000" COMPAT="3" $RUN
            SOC="xm530" OSMEM="35M" TOTALMEM="64M" HARDWARE="XM530_80X30T_8M" DEVID="000309ED" FLASH_SIZE="0x800000" COMPAT="3" $RUN

            SOC="xm530" OSMEM="35M" TOTALMEM="128M" HARDWARE="XM530_80X50_8M" DEVID="00030679" FLASH_SIZE="0x800000" COMPAT="3" $RUN
            SOC="xm530" OSMEM="35M" TOTALMEM="128M" HARDWARE="XM530_85X50_8M" DEVID="0003068D" FLASH_SIZE="0x800000" COMPAT="3" $RUN

            SOC="xm530" OSMEM="35M" TOTALMEM="64M" HARDWARE="XM530_R80X20-PQ_8M" DEVID="00030695" FLASH_SIZE="0x800000" COMPAT="3" $RUN

            SOC="xm510" TOTALMEM="32M" HARDWARE="50X10_32M" DEVID="00023650" FLASH_SIZE="0x800000" COMPAT="2" $RUN
            SOC="xm510" TOTALMEM="32M" HARDWARE="53X13_32M" DEVID="00023651" FLASH_SIZE="0x800000" COMPAT="2" $RUN

            SOC="nt98562" SENSOR="sc401ai" TOTALMEM="64M" HARDWARE="IPC_NT98562_80N40_S38" DEVID="000629G3" FLASH_SIZE="0x800000" $RUN
            SOC="nt98566" SENSOR="sc501ai" TOTALMEM="128M" HARDWARE="IPC_NT98566_80N50_S38" DEVID="000639H4" FLASH_SIZE="0x800000" $RUN
            SOC="nt98566" SENSOR="sc501ai" TOTALMEM="128M" HARDWARE="IPC_NT98566_85N80_S38" DEVID="000639I2" FLASH_SIZE="0x800000" $RUN

        continue-on-error: true
      - name: Create release
        uses: actions/create-release@v1
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          body: |
            Transition firmware for XiongMai-based boards
          draft: false
          prerelease: ${{ env.PRERELEASE }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out/*
          file_glob: true
          tag: ${{ env.TAG_NAME }}
          overwrite: true
#       - name: Setup tmate session
#         if: ${{ failure() }}
#         uses: mxschmitt/action-tmate@v3   
